version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.6
